### ISSUE TITLE
Remove prebuilt binaries and non-distributable files

### ISSUE THREAD

**Issue by dvzrv** [EmbeddedSynth/sonivox-fork#2]
Hi! @krop made me aware of some files in this repository, which are not used for the build of sonivox and should also not exist in this repository.

Please make sure to remove the prebuilt binaries:

* https://github.com/pedrolcl/sonivox/blob/31d626436117416d8ba175ad791a83bb92efff1c/arm-wt-22k/bin/arm-wt-22k
* https://github.com/pedrolcl/sonivox/blob/31d626436117416d8ba175ad791a83bb92efff1c/arm-wt-22k/lib/libarm-wt-22k.a

and the zip file https://github.com/pedrolcl/sonivox/blob/31d626436117416d8ba175ad791a83bb92efff1c/arm-wt-22k/misc/MMAPI.zip as it seems to contain a directory that is marked as not being allowed to be redistributed.

**Comment by pedrolcl** [comment]
I'm adding here Dominique @DimStar77 and Christian @marillat because they are involved in the packaging for their respective distributions, so they should be interested in this issue affecting the usability of Drumstick based applications like [VMPK](https://github.com/pedrolcl/VMPK) and [dmidiplayer](https://github.com/pedrolcl/dmidiplayer).

First of all: I agree to remove the requested components from the repository, so the generated tarballs don't include those in future releases. Fixed in:  c103a4e

The next release of sonivox will include this fix, which will be published ASAP. Anyway, in my opinion there are no legal issues at all, because:

This fork included every file from the original AOSP repository, as can be verified by the git log. So if there are any legal complains, they should be addressed to Google instead. And indeed, all the issues have been examined at the courts already:

https://en.wikipedia.org/wiki/Google_LLC_v._Oracle_America,_Inc.

About the [MMAPI.zip](https://github.com/pedrolcl/sonivox/blob/31d626436117416d8ba175ad791a83bb92efff1c/arm-wt-22k/misc/MMAPI.zip) file, there are several articles explaining why it wasn't a real issue:

https://www.fudzilla.com/news/21639-android-patent-fraud-turns-out-to-be-pants

https://arstechnica.netblogpro.com/information-technology/2011/01/new-alleged-evidence-of-android-infringement-isnt-a-smoking-gun/

**Comment by pedrolcl** [comment]
CC: @GvMariani
